spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: release

server:
  port: 9999
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: true